In [33]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\talya\onedrive\desktop\ml01\python\venv\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\talya\onedrive\desktop\ml01\python\venv\lib\site-packages (from pandas) (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\talya\onedrive\desktop\ml01\python\venv\lib\site-packages (from pandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\talya\onedrive\desktop\ml01\python\venv\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\talya\onedrive\desktop\ml01\python\venv\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\talya\onedrive\desktop\ml01\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [34]:
import pandas as pd

In [35]:
data=[6,7,8,9,0]
series=pd.Series(data)
print("series\n", series)

series
 0    6
1    7
2    8
3    9
4    0
dtype: int64

In [36]:
data=[1,2,3,4]
index = ['a','b','c','d']
pd.Series(data,index=index)

a    1
b    2
c    3
d    4
dtype: int64

In [37]:
# dataframe
# create a dataframe from a dictionry oof list

data = {
    'Name':['krish','jack','john'],
    'Age':[20,30,40],
    'City':['delhi','gurugram','kurukshetra']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age         City
0  krish   20        delhi
1   jack   30     gurugram
2   john   40  kurukshetra
<class 'pandas.core.frame.DataFrame'>

In [38]:
data = [
    {'Name':'aakash', 'Age':20,'city':'kurukshetra'},
    {'Name':'aakash', 'Age':20,'city':'kurukshetra'},
    {'Name':'aakash', 'Age':20,'city':'kurukshetra'},
    {'Name':'aakash', 'Age':20,'city':'kurukshetra'},
    {'Name':'aakash', 'Age':20,'city':'kurukshetra'},
]
df=pd.DataFrame(data)
print(df)

     Name  Age         city
0  aakash   20  kurukshetra
1  aakash   20  kurukshetra
2  aakash   20  kurukshetra
3  aakash   20  kurukshetra
4  aakash   20  kurukshetra

In [39]:
df['Name']

0    aakash
1    aakash
2    aakash
3    aakash
4    aakash
Name: Name, dtype: object

In [40]:
df.loc[0]

Name         aakash
Age              20
city    kurukshetra
Name: 0, dtype: object

In [41]:
df.iloc[0]

Name         aakash
Age              20
city    kurukshetra
Name: 0, dtype: object

In [42]:
df.iloc[0][0]

C:\Users\talya\AppData\Local\Temp\ipykernel_1412\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'aakash'

In [43]:
df

     Name  Age         city
0  aakash   20  kurukshetra
1  aakash   20  kurukshetra
2  aakash   20  kurukshetra
3  aakash   20  kurukshetra
4  aakash   20  kurukshetra

In [44]:
#accessing a specified element
df.at[2,'Age']

np.int64(20)

In [45]:
df.iat[2,2]

'kurukshetra'

In [46]:
#adding a coloum
df['Salary']=[2,3,4,5,6]
df

     Name  Age         city  Salary
0  aakash   20  kurukshetra       2
1  aakash   20  kurukshetra       3
2  aakash   20  kurukshetra       4
3  aakash   20  kurukshetra       5
4  aakash   20  kurukshetra       6

In [47]:
df.drop('Salary',axis=1,inplace=True)

In [48]:
df

     Name  Age         city
0  aakash   20  kurukshetra
1  aakash   20  kurukshetra
2  aakash   20  kurukshetra
3  aakash   20  kurukshetra
4  aakash   20  kurukshetra

In [49]:
df['Age']+1

0    21
1    21
2    21
3    21
4    21
Name: Age, dtype: int64

In [50]:
df.drop(0,inplace=True)

In [51]:
df

     Name  Age         city
1  aakash   20  kurukshetra
2  aakash   20  kurukshetra
3  aakash   20  kurukshetra
4  aakash   20  kurukshetra